image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: script  # будем использовать свой скрипт сборки

build_script:
  - https://postman-echo.com
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации