image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

#build: on

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации